"""empty message

Revision ID: 310702add7c4
Revises: eb01253a94d5
Create Date: 2026-01-29 22:24:12.013048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310702add7c4'
down_revision = 'eb01253a94d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    op.drop_table('messages')
    # ### end Alembic commands ###
